version: '3'

services:
  php:
    image: ghcr.io/aeroclub-de-saint-omer/php:latest
    command: /bin/bash -c 'symfony server:stop; symfony server:start --port 8001'
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8001:8001
  yarn:
    image: node:16
    working_dir: /app
    tty: true
    volumes:
      - .:/app:delegated
    command: /bin/sh -c "yarn install && yarn watch"
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5430:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###
