on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: ./.github/workflows/docker.yaml
        with:
          IMAGE_NAME: ${{ steps.meta.outputs.tags }}
          IMAGE_LABELS: ${{ steps.meta.outputs.labels }}
  deploy:
    name: Deploy ${{ inputs.ENV }}
    environment: ${{ inputs.ENV }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo The username is ${{ inputs.username }}
      - name: healthcheck
        run: echo The username is ${{ inputs.username }}


