name: Security
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_call:

jobs:
  check_security:
    name: Symfony Check Security
    runs-on: ubuntu-latest
    container: ghcr.io/aeroclub-de-saint-omer/php:latest
    steps:
      - uses: actions/checkout@master
      - name: security:check
        run: symfony security:check