name: Tests
on: [push, pull_request]
jobs:
  security:
    name: Symfony Check Security
    uses: ./.github/workflows/security.yaml
  lint:
    name: Linter (PhpStan)
    needs: [security]
    runs-on: ubuntu-latest
    container: ghcr.io/aeroclub-de-saint-omer/php:latest
    steps:
      - uses: actions/checkout@master
      - name: Composer
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress
      - name: Lint
        run: ./vendor/bin/phpstan analyse  --memory-limit=-1
  test:
    name: Test Unitaire (PHP Unit)
    needs: [security]
    runs-on: ubuntu-latest
    container: ghcr.io/aeroclub-de-saint-omer/php:latest
    steps:
      - uses: actions/checkout@master
      - name: Composer
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress
      - name: Lint
        run: ./vendor/bin/phpunit